### ISSUE TITLE
Body segmentation QA: stretched/noisy/out of body tissue in lower torso (low SNR, TotalSegMRI)

### ISSUE THREAD

**Issue by mathieuboudreau** [shimming-toolbox/b0-fieldmap-realistic-simulation#14]
After getting the initial B0 sim results,

<img width="861" alt="Screenshot 2024-10-31 at 10 35 33 PM" src="https://github.com/user-attachments/assets/ebff9428-cae6-4df7-9291-630e1131d783">

I noticed that in the saggital slices, some out-of-body tissue segmentations remained in some subjects, ie

![Screenshot 2024-11-02 at 2 57 56 PM](https://github.com/user-attachments/assets/f31b865d-9dd8-4ec6-9530-12995c290dba)

For that example subject, I tried to automate removal using keep-largest-island & gaussian smoothing via Slicer 3D, but the kernel size needed to really smooth it out was lead to excessive smoothing of other features (eg head) and shrinking. 

Thus, I decided that some additional manual segmentation would be needed for such subjects to roughly remove these bad segmentations from TotalSegMRI (likely due to low SNR in these regions). 

I went through and visualized the body segmentation through 3D rendering in Slicer 3D to get a better view, and did this for all subject. A lot of subjects were good to my eye, eg

![Screenshot 2024-11-02 at 2 21 46 PM](https://github.com/user-attachments/assets/1e537c01-d13b-4a1f-aa34-64c0098abcaf)

 I kept a list of the subjects I think could benefit from some manual segmentation before the pipeline, and **found that these types of issues impacted 31 subjects**. Below I'll list all screenshots for these subjects to show the variability between slight correction needed vs major. Unfortunately Slicer3D only has a spherical paintbrush in 3D, so I might cause some shallow "craters", but I'm hoping that 1) the result will be better than the alternative of not doing this manual correction and 2) that the smoothing step later on will mostly remove this.
 
 Here's all the cases I'm talking about (hopefully github is ok with 31 images, I'll make it in a collapsable block:
 
 <details>

![Screenshot 2024-11-02 at 2 24 23 PM](https://github.com/user-attachments/assets/faf238a7-4df7-4af8-ba10-daae4b50ba95)

![Screenshot 2024-11-02 at 2 24 23 PM](https://github.com/user-attachments/assets/60c5434e-8a84-4e5e-bc84-1d877e356e50)

![Screenshot 2024-11-02 at 2 26 12 PM](https://github.com/user-attachments/assets/53bca01a-2fb2-4427-b9b8-7276e6999ba4)

![Screenshot 2024-11-02 at 2 26 38 PM](https://github.com/user-attachments/assets/e37673af-fca4-4b67-8de6-9c1898391b73)

![Screenshot 2024-11-02 at 2 27 11 PM](https://github.com/user-attachments/assets/a5f86e48-f92a-42aa-b6ea-279c13a07298)

![Screenshot 2024-11-02 at 2 28 01 PM](https://github.com/user-attachments/assets/fcf5296d-6f65-42d6-a4fb-4d3f284ccbb7)

![Screenshot 2024-11-02 at 2 29 04 PM](https://github.com/user-attachments/assets/1d7d12b3-4df7-4e64-ae6b-5a6df393059c)

This next one is mostly due to a bad segmentation of the right breast tissue, it makes somewhat of a cave - not sure if I can improve this:

![Screenshot 2024-11-02 at 2 29 45 PM 1](https://github.com/user-attachments/assets/9ed45f62-5014-433a-afc1-56528fd43f34)

![Screenshot 2024-11-02 at 2 38 27 PM](https://github.com/user-attachments/assets/d7e2811d-57ea-4ee7-893c-89465d97ab0d)

This next subject's lower torso simply stopped segmentted; maybe I can brush it up to the boundary to remove this hash air-tissue interface:

![Screenshot 2024-11-02 at 2 38 49 PM 1](https://github.com/user-attachments/assets/c55f428e-c2f6-4253-80b0-a558cc44831e)

![Screenshot 2024-11-02 at 2 39 33 PM](https://github.com/user-attachments/assets/89fcb59f-99ea-489f-8f95-582526398630)

![Screenshot 2024-11-02 at 2 40 41 PM](https://github.com/user-attachments/assets/06e600bf-bbed-4148-a88a-efc3a409d754)

Due to the apparent larger size of this next subject, the overally chest/belly is really roughly segmented. Not sure if I'll fix this manually or just leave it to smoothing.
![Screenshot 2024-11-02 at 2 41 47 PM](https://github.com/user-attachments/assets/316b97cd-eb19-4860-bc54-85071a8ab954)

![Screenshot 2024-11-02 at 2 42 26 PM](https://github.com/user-attachments/assets/937a6afe-fd97-4dcc-b82e-b89947324be1)

![Screenshot 2024-11-02 at 2 43 02 PM](https://github.com/user-attachments/assets/a829ffad-94c8-49e8-adc9-9ea96f51ecb7)

![Screenshot 2024-11-02 at 2 43 36 PM](https://github.com/user-attachments/assets/1dc60ec9-4986-4999-ac12-79eab1d67560)

![Screenshot 2024-11-02 at 2 44 18 PM](https://github.com/user-attachments/assets/c1598786-4e0a-4fef-8c7f-011e2823d0da)

This next one also had lung tissue that was oddly segmented nowhere near the lungs:
![Screenshot 2024-11-02 at 2 44 38 PM](https://github.com/user-attachments/assets/a639694c-85b9-4be3-a3c3-a70abf26f987)

![Screenshot 2024-11-02 at 2 46 10 PM](https://github.com/user-attachments/assets/cdb37f45-146a-4a51-bdda-596b895652ce)

![Screenshot 2024-11-02 at 2 46 22 PM](https://github.com/user-attachments/assets/815dc96a-74e1-4ad4-94e8-719e332e9df0)

![Screenshot 2024-11-02 at 2 46 58 PM](https://github.com/user-attachments/assets/31e14508-589e-4c97-99f1-d8cc38ab4ca1)

![Screenshot 2024-11-02 at 2 47 14 PM](https://github.com/user-attachments/assets/f3d0c06b-a010-46bd-9805-4a8212ce1e35)

![Screenshot 2024-11-02 at 2 47 32 PM](https://github.com/user-attachments/assets/ef7400e3-aea4-4871-b696-4781b0dc78df)

![Screenshot 2024-11-02 at 2 47 52 PM](https://github.com/user-attachments/assets/2dfd671d-e35a-4fdf-b06d-d8e9f74796dd)

![Screenshot 2024-11-02 at 2 48 43 PM](https://github.com/user-attachments/assets/9201fcbc-20f6-4590-b194-45a2e119a304)

![Screenshot 2024-11-02 at 2 49 28 PM](https://github.com/user-attachments/assets/184165e8-27a7-4b6f-8bb6-36fc79d27193)

I think the size of this next subject also caused noisy segmentation  in the lower torso
![Screenshot 2024-11-02 at 2 52 08 PM](https://github.com/user-attachments/assets/39bd142b-6ff3-4dc7-91b1-d28a677c8cc5)

This next one's lower torso's segmentation is pretty bad, not sure if I can manually fix this quickly. Also note the mouth, this happened for a few subjects - wont fix these.
![Screenshot 2024-11-02 at 2 52 34 PM](https://github.com/user-attachments/assets/96881430-58d1-4e7f-99e9-a5ae5970b05f)

![Screenshot 2024-11-02 at 2 54 07 PM](https://github.com/user-attachments/assets/e825a79f-97cc-48b7-b214-8c49a521b186)

![Screenshot 2024-11-02 at 2 54 44 PM](https://github.com/user-attachments/assets/d57791b4-93cb-4d22-95cb-c9b8d3fbcbbc)

![Screenshot 2024-11-02 at 2 55 24 PM](https://github.com/user-attachments/assets/be068473-9abd-42b2-80a8-133684284d96)

</details>

I'll try to manually fix as many of these tonight and/or tomorrow night, going from most severe to less severe, and will resimulate the B0 maps following the correction and added island removal and smoothing ASAP

**Comment by sriosq** [comment]
Hello Mathieu, could you tell me which set of segment editions you followed to smooth the body? I would also like to smooth the body from my segmentation. Thank you!

**Comment by mathieuboudreau** [comment]
>Hello Mathieu, could you tell me which set of segment editions you followed to smooth the body? I would also like to smooth the body from my segmentation. Thank you!

I've only tested it with one subject so far, but what I'm going to go with is:

https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/blob/61bcd2e91be94111d0e2cfa7d706eea712af3c6d/b0realsim/slicer_scripts/smooth_segment.py#L85-L114

reproduced here:
```python

       # Keep largest island
        largest_island(segmentEditorWidget)

        # Smooth gaussian 5 or 10 mm, might need to adjust the grow step
        gaussian(segmentEditorWidget, 3)
        
        # Grow the segment
        grow(segmentEditorWidget, 3)

```

**Comment by mathieuboudreau** [comment]
Finished the manual corrections - near the end I figured out how to apply smoothing using a brush instead of whole-volume; some of the earlier subjects I removed out-of-body tissue segmentations could have greatly benefitted from this; I don't have time now, but I'll open an issue to revisit this later

**Comment by mathieuboudreau** [comment]
Here's a gif of the before and after the corrections:

![myimage](https://github.com/user-attachments/assets/0f5d5ea6-1781-4fc0-b3ea-775f52f70b84)

Next I'd like to investigate why some subjects have high B0 values in their lower torso; I suspect that possible a few voxels at the bottom boundary aren't fully assigned as tissue and thus air in the chi map, and when we add padding we introduce this pocket of air there. I saw this  happen in some of them that I was manualy correcting ad tried to "paint" in as much as I could, but didn't go through and compared one case of a "good"/blue toros vs red to see the difference.

Here's what I mean:

![Screenshot 2024-11-04 at 10 19 58 AM](https://github.com/user-attachments/assets/9ff76b0b-d8af-45dd-8013-3c118a62da89)
