### ISSUE TITLE
Subject `JD` wrongly pushed on Open Neuro

### ISSUE THREAD

**Issue by NathanMolinier** [shimming-toolbox/b0-fieldmap-realistic-simulation#19]
## Description

It looks like the subject `JD` of the recent [pushed](https://openneuro.org/datasets/ds005616/versions/1.0.0) dataset `whole-spine` was wrongly pushed.

Based on @jcohenadad comment
> We got the OK from Marseille (Virginie Callot) to upload the T1w data, except these subjects:
> 
> * ED
> * JD
> * JW

Tagging @mathieuboudreau 

## Related issue

https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/issues/9

**Comment by mathieuboudreau** [comment]
@NathanMolinier Where? I don't see that subject's T1w data in there,

<img width="348" alt="Screenshot 2024-11-08 at 11 46 38 AM" src="https://github.com/user-attachments/assets/17ca035a-5519-4ee9-ba45-c3c73b84d343">

**Comment by NathanMolinier** [comment]
Oooh that's my bad indeed, I got confused with the derivatives folder ! I thought that you did not keep labels from subjects that were not included inside the dataset

**Comment by mathieuboudreau** [comment]
@NathanMolinier no worries - always good to double check! 

Here is where it was stated that only the T1w and T2w had to be omitted: https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/issues/9#issuecomment-2445651708
