### ISSUE TITLE
Cleanup SAMSEG segmentation

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/b0-fieldmap-realistic-simulation#5]
SAMSEG segmentation has the following useful classes:
- 258: body
- 165: skull
- 259: eye

We need to create a separate file for each of them, to be able to pre-process some of these labels, eg: smooth the skull one, as it is very noisy, see orange label below:
![image](https://github.com/user-attachments/assets/37409c99-2a28-4b4b-a76e-274892b2b5b7)

## Motivation for the body class

Even though the body class that @CharlesPageot did already includes the head (see https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/issues/4#issue-2581790536), the SAMSEG head body is of better quality. See below comparison between the two body labels, with the one from Charles missing part of the head:

![ezgif-1-95d1200de5](https://github.com/user-attachments/assets/ab7597f5-a2dd-41dc-b01c-255ac8634edd)

**Comment by mathieuboudreau** [comment]
Done via Slicer in https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/blob/4f3c471db542fa9b12f308aaeece401323980965/b0realsim/slicer_scripts/smooth_segment.py
